library(shiny)
library(sf)
library(units)
library(leaflet)
library(leafpop)
library(dplyr)
library(curl)

##########Load Data############

vars<- c("Parcel ID"="ParcelID")
#read in main structure data

main_url = "https://github.com/gsaldutti-dlba/scattered-site-bundles/blob/main/appData/main.RDS?raw=true"
main <- readRDS(gzcon(url(main_url))) %>%
  st_transform(4326) %>%
  st_cast("POLYGON")

#read in potential site data
sites_url <- "https://github.com/gsaldutti-dlba/scattered-site-bundles/blob/main/appData/sites.RDS?raw=true"
sites <- readRDS(gzcon(url(sites_url))) %>%
  st_transform(4326) %>%
  st_cast("POLYGON") 

#format distance col
sites$nearest_dist <- as.numeric(sites$nearest_dist)

#read in distance matrix
matrix_url<-"https://github.com/gsaldutti-dlba/scattered-site-bundles/blob/main/appData/distance-matrix.RDS?raw=true"
mat_distances <- readRDS(gzcon(url(matrix_url)))

#set color palette
dist_palette <- "magma"

districts <- readRDS(here::here('appData/districts.RDS')) %>% st_cast("POLYGON") %>%st_cast("LINESTRING")
#lra_url <- "https://github.com/gsaldutti-dlba/scattered-site-bundles/blob/main/appData/LRA.RDS?raw=true"


lra <- readRDS(here::here('appData/LRA.RDS')) %>% st_transform(4326) %>% st_cast("POLYGON") %>%st_cast("LINESTRING")

#### ui ####
ui <- fluidPage(#create fluid page
  
  div(class='outer', #create div within page for defining css style
      tags$head(
    # Include our custom CSS
        includeCSS("style.css")
        ),
    
  fluidPage(
    titlePanel("Bundled Site Proximity App"), #set app title
    leafletOutput("siteMap", height="700px"), #set map as plot object
    absolutePanel(#input select 
      id = "controls", class = "panel panel-default", fixed = TRUE,
      draggable = TRUE, top = 60, left = "auto", right = 20, bottom = "auto",
      width = 330, height = "auto",#creates css for positioning of input panel
      h2("Data Filters"), #create header object for titling input panel
      
      #shiny input definitions
      selectizeInput("parcelSearch", "Search Main Structure Parcel ID:" #id and title
                     , choices=c("-", main$ParcelID)) #append - for default selection
      ,numericInput("distInput", "Filter Distance:" #id and titling
                    , step=100, value=2000 #set scroll steps and default value
                    , min=0, max=100000) #min max values
      
      ),    #end absolute panel
    p("Parcel IDs of potential bundle sites:"),
    p(textOutput("parcelString")) 

    )#end fluid page internal
  )#end div
  ) #end fluid page external

#### server ####
server <- function(input, output, session) { #create plotly server setup
  
  
  ###########called within render
  #create palette for scaling colors using distance to nearest
  #this is used in the defualt plot
  pal <- colorNumeric(dist_palette, domain = c(0, 3000))
  
  
  #render default map showing sites coded by distance to nearest neighbor
  output$siteMap <- renderLeaflet({
    leaflet() %>% #instantiate leaflet
      addProviderTiles("Esri.WorldGrayCanvas") %>% #add basemap
      addPolylines(data=districts) %>%
      
      #add all potential bundle sites
    #   addPolygons(data=sites
    #               ,opacity  = 1 #set alpha
    #               ,fillOpacity = .7 #set fill alpha
    #               ,color=~pal(nearest_dist) #color sites according to nearest neighbor
    #               ,weight=5
    #               ,group="410"
    #               ) %>% #set group for clearing 
    # addPolygons(data=main #plot all identified structures as main 
    #             ,weight=3
    #             ,group="400") %>% #set line weight and group for clearing
    addLayersControl(overlayGroups = c("LRA", "Districts"),
                     position='topleft')
     
  }) #end initial leaflet map render
  
  
  #########called within observe 
  
  #create color palette for coloring main sites based on selection
  #selected sides will be blue, all others will be gray
  ##data col (T,F) is generated by reactive element below
  main_color_pal <- colorFactor(c("#80ebff", "green") 
                                , domain=c(F, T)
                                , alpha=T)
  
  
  #create filtered sites data frame
  #this appends pre computed distance to the selected main site
  #as determined by user input 
  filter_sites <- reactive({
    
    #create dataframe that contains the distance to the selected features
    if(req(input$parcelSearch) != "-"){ #require that search is not default
      #get the index of parcel match
      index <- which(main$ParcelID==input$parcelSearch) 
      #bind pre-computed distances to selected parcel
      sites <- cbind(sites, as.integer(mat_distances[,index])) 
      
      #rename col for mapping
      colnames(sites)[length(colnames(sites))-1] <- "distance_from_selected"
      return(sites)
    }

  }) #end reactive element
  
  rctv_parcel_string <- reactive({
    filter_site_string <- paste0(filter_sites()[filter_sites()$distance_from_selected <=
                                     input$distInput,]$ParcelID_structure, collapse=",")
    
  })
  
  #create mapping for selected parcel 
  #will append t/f to is_parcel for coloring blue/gray used in 
  #main_color_pal reactive element
  filter_main <- reactive ({
    #require that input is present and is "-"
    if(req(input$parcelSearch) =="-") {
      main #make no changes if no parcel is selected
    } else {
      #if a parcel is selected, append col for color mapping
      main$is_parcel <- ifelse(main$ParcelID == input$parcelSearch,
                               T, F)
    }
    main #return dataframe 
  }) #end filter_main reactive
  
  #reactive element for creating color palette 
  pal_max_distance <- colorNumeric(dist_palette, 
                               #map domain to max matrix
                               #creates consistent color mapping 
                        domain = c(0, 10000))
  
  #observer that will redraw plot as inputs change
  observe({
   
    
    #if parcel input is not default 
    if(input$parcelSearch != "-") {
      filter_sites <- filter_sites()[filter_sites()$distance_from_selected <=
                                       input$distInput,]
      print(filter_sites)
      req(filter_main()) #require reactive dataframe
    #set proxy to update  
    leafletProxy("siteMap") %>%
      clearShapes() %>% #clear shapes
      clearControls() %>% #clear legend
      addPolylines(data=lra, color='blue', weight=3, group='LRA') %>%
      addPolylines(data=districts,
                   weight=2,
                   color="purple",
                   group='Districts') %>%
      
      #add reactive sites dataframe, including distance to selected main site
      addPolygons(
        data= filter_sites #filter data based on input distance
                     #end data input
                      #map color using max distance palette
        ,color = ~pal_max_distance(distance_from_selected)
        ,opacity  = .8 #set opacity
        ,fillOpacity = 1 #set fill opacity
        ,weight=2
        ,group="410" #group for removing 
        ,popup=
          paste0(
              "<strong>Address: </strong>", filter_sites$Address, "</br>",
            "<strong>ParcelID: </strong>", filter_sites$ParcelID_structure,"</br>",
            "<strong>Neighborhood: </strong>", filter_sites$Neighborhood ,"</br>",
            #"<strong>Zip: </strong>", filter_sites$PropertyZIPCode ,"</br>",
            "<strong>District: </strong>", filter_sites$CouncilDistrict ,"</br>",
            "<strong>Property Class: </strong>", filter_sites$PropertyClass,"</br>",
            "<strong>Distance to selected: </strong>", as.integer(filter_sites$distance_from_selected), "ft"
                    )) %>%
      
      addLegend("bottomright"
                , pal = pal_max_distance #set color pal
                , values = ~distance_from_selected[distance_from_selected < 10000] #set variable to map
                ,title = HTML("Distance to</br>
                            selected structure (ft)"), #format title
                labFormat = labelFormat(suffix = "ft"), #add ft
                opacity = 1, data=filter_sites() #set opacity and data
      ) %>%
      #add main structures
      addPolygons(data=filter_main()
                  ,weight=5
                  , group="400" #set group id for clearing
                  ,col=~main_color_pal(is_parcel) #trigger selected coloring, blue/gray
                  ,popup=
                    paste0(
                      "<strong>Case Number: </strong>", filter_main()$CaseCaseNumber, "</br>",
                      "<strong>Address: </strong>", filter_main()$CaseAddress, "</br>",
                      "<strong>Parcel ID: </strong>", filter_main()$ParcelID, "</br>"
                    )
      ) %>%
      addLegend("bottomright"
                , colors=c("green","#80ebff") 
                ,labels = c("Selected Structure","Unselected Structures")) 
    
    
    } else { #if default view is selected 
      
      #this recreates the default load map
      leafletProxy({"siteMap"}) %>% #update map
        #clear all
        clearShapes() %>%
        clearControls() %>%
        addPolylines(data=lra, color='blue', weight=3, group='LRA') %>%
        addPolylines(data=districts,
                     weight=2,
                     color="purple",
                     group="Districts") %>%
        
        #add non-reactive site data
        addPolygons(data=sites[sites$nearest_dist <= input$distInput,]
                    ,opacity  = .4
                    ,fillOpacity = .4
                    ,color=~pal(nearest_dist)
                    ,weight=2
                    ,group="410"
                    ,popup=paste0(
                    #"<strong>Case Number: </strong>", sites$CaseNumber, "</br>",
                    "<strong>Address: </strong>", sites$Address, "</br>",
                    "<strong>ParcelID: </strong>", sites$PropertyParcelID_structure,"</br>",
                    "<strong>Neighborhood: </strong>", sites$Neighborhood ,"</br>",
                    #"<strong>Zip: </strong>", sites$PropertyZIPCode ,"</br>",
                    "<strong>District: </strong>", sites$CouncilDistrict ,"</br>",
                    "<strong>Property Class: </strong>", sites$PropertyClass,"</br>",
                    "<strong>Distance to Nearest: </strong>", as.integer(sites$nearest_dist), "ft", "</br>",
                    "<strong>Nearest Parcel: </strong>", sites$ParcelID_site)
                    ) %>%
        
        #add legend with nearest neighbor coding
        addLegend("bottomright", pal = pal, values = c(0,3000),
                  title = HTML("Distance to</br>
                             Nearest structure (ft)"),
                  labFormat = labelFormat(suffix = "ft"),
                  opacity = 1, data=sites
                  )  %>%
        
        #add non-reactive main data
        addPolygons(data=main
                    ,color='green'
                    ,weight=4
                    , group="400"
                    ,opacity=.8
                    ,popup=
                      paste0(
                        "<strong>Case Number: </strong>", main$CaseCaseNumber, "</br>",
                        "<strong>Address: </strong>", main$CaseAddress, "</br>",
                        "<strong>Parcel ID: </strong>", main$ParcelID, "</br>")) %>%
        addLegend("bottomright", colors="green" ,labels = "Main Structure")
    } #end else statement
    }) #end observe container
  
  
  output$parcelString <- renderText({rctv_parcel_string()})
  

  
      } #end session 

shinyApp(ui,server) #run appy
